### ISSUE TITLE
Create Spell Grammar

### ISSUE THREAD

**Issue by whiterook6** [whiterook6/fibonacci#1]
Something like this:

```
symbol: string // an rpg-awesome icon
cooldown: int // how many seconds between uses, at minimum
cost [ string: int ]* // key-values of how much of a resource a player needs. HP, MP, etc.
effects:
  self: [ string: int ]* // key-values of what to do to self when it hits
  target: [ string: int ]* // key-values of what to do to a target when it hits
  others: [ string: int ]* // key-values of what to do to all others
color: #hex // color of the spell icon
```
